apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-universe
  name: hello-universe
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: hello-universe
  sessionAffinity: None
  type: LoadBalancer
